import json
import sys
import shutil

NB_PATH = "experimentalModel2.ipynb"
BAK_PATH = "experimentalModel2.ipynb.bak_figure_cell"

# Back up the notebook before editing.
shutil.copy2(NB_PATH, BAK_PATH)

with open(NB_PATH) as f:
    nb = json.load(f)

# ------------------------------------------------------------------
# Markdown cell explaining what to run.
# ------------------------------------------------------------------
markdown_src = (
    "## Standalone Figure 3 + Figure 4 data preparation (load-only)\n"
    "\n"
    "Run **only** the code cell below, then run the **Figure 3 + Figure 4** cell.\n"
    "\n"
    "- No training is performed.\n"
    "- It loads QTDB + LUDB, builds R-centred beats (PRE=120, POST=320),\n"
    "  loads the pretrained R3 and R6 models, and computes the predictions\n"
    "  needed for Figure 3 (QTDB) and Figure 4 (LUDB).\n"
)

markdown_cell = {
    "cell_type": "markdown",
    "metadata": {},
    "source": markdown_src.splitlines(keepends=True),
}

# ------------------------------------------------------------------
# Standalone code cell (load-only, no training).
# ------------------------------------------------------------------
code_src = (
    "# ============================================================\n"
    "# STANDALONE FIGURE 3 + FIGURE 4 DATA PREP\n"
    "# (No training. Run this cell, then run the Figure 3 + Figure 4 cell.)\n"
    "# ============================================================\n"
    "\n"
    "%pip install -q wfdb scipy scikit-learn torch matplotlib pandas\n"
    "\n"
    "from pathlib import Path\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "from scipy.signal import butter, sosfiltfilt, find_peaks, resample_poly\n"
    "from sklearn.model_selection import train_test_split\n"
    "import wfdb\n"
    "import torch\n"
    "import torch.nn as nn\n"
    "from torch.utils.data import TensorDataset, DataLoader\n"
    "\n"
    "REPO_ROOT = Path.cwd()\n"
    "QTDB_DIR = REPO_ROOT / \"physionet.org/files/qtdb/1.0.0\"\n"
    "LUDB_DIR = REPO_ROOT / \"physionet.org/files/ludb/1.0.1/data\"\n"
    "assert QTDB_DIR.exists(), f\"No QTDB data here: {QTDB_DIR}\"\n"
    "assert LUDB_DIR.exists(), f\"No LUDB data here: {LUDB_DIR}\"\n"
    "\n"
    "PRE = 120\n"
    "R5_POST = 320\n"
    "R5_BEAT_LENGTH = PRE + R5_POST\n"
    "BATCH_SIZE = 64\n"
    "\n"
    "MODEL_LOAD_PATH_R3 = \"best_ml2_rpeak_guided_focal_unweighted.pth\"\n"
    "MODEL_LOAD_PATH_R6_LUDB = \"best_ml2_r6_time_ludb10.pth\"\n"
    "NORMALIZATION_LOAD_PATH = \"best_ml2_rpeak_guided_normalization.npz\"\n"
    "for p in [MODEL_LOAD_PATH_R3, MODEL_LOAD_PATH_R6_LUDB, NORMALIZATION_LOAD_PATH]:\n"
    "    assert Path(p).exists(), f\"Missing file: {p}\"\n"
    "\n"
    "\n"
    "def generate_labels(ecg, ann):\n"
    "    labels = np.zeros(len(ecg), dtype=np.int64)\n"
    "    start, wave_kind = None, None\n"
    "    for sample, symbol in zip(ann.sample, ann.symbol):\n"
    "        if symbol == \"(\":\n"
    "            start, wave_kind = sample, None\n"
    "        elif symbol == \"p\":\n"
    "            wave_kind = 1\n"
    "        elif symbol == \"N\":\n"
    "            wave_kind = 2\n"
    "        elif symbol == \"t\":\n"
    "            wave_kind = 3\n"
    "        elif symbol == \")\" and start is not None and wave_kind is not None:\n"
    "            labels[start:sample + 1] = wave_kind\n"
    "            start, wave_kind = None, None\n"
    "    return labels\n"
    "\n"
    "\n"
    "def to_pt_labels(labels):\n"
    "    out = labels.copy()\n"
    "    out[out == 2] = 0\n"
    "    out[out == 3] = 2\n"
    "    return out\n"
    "\n"
    "\n"
    "def pan_tompkins_r_peaks(ecg, fs, lowcut=5.0, highcut=18.0):\n"
    "    nyquist = fs / 2\n"
    "    sos = butter(3, [lowcut / nyquist, highcut / nyquist], btype=\"bandpass\", output=\"sos\")\n"
    "    bandpassed = sosfiltfilt(sos, ecg)\n"
    "    derivative = np.convolve(bandpassed, np.array([-1, -2, 0, 2, 1]) * fs / 8, mode=\"same\")\n"
    "    integrated = np.convolve(derivative ** 2, np.ones(max(1, round(0.150 * fs))) / max(1, round(0.150 * fs)), mode=\"same\")\n"
    "    candidates, _ = find_peaks(integrated, distance=max(1, round(0.20 * fs)))\n"
    "    boot = candidates[candidates < min(len(ecg), round(2 * fs))]\n"
    "    boot = boot if len(boot) else candidates\n"
    "    spki = np.percentile(integrated[boot], 90) if len(boot) else 0.0\n"
    "    npki = np.percentile(integrated[boot], 25) if len(boot) else 0.0\n"
    "    accepted = []\n"
    "    for peak in candidates:\n"
    "        threshold = npki + 0.25 * (spki - npki)\n"
    "        if integrated[peak] >= threshold:\n"
    "            accepted.append(peak)\n"
    "            spki = 0.125 * integrated[peak] + 0.875 * spki\n"
    "        else:\n"
    "            npki = 0.125 * integrated[peak] + 0.875 * npki\n"
    "    search = round(0.10 * fs)\n"
    "    refined = []\n"
    "    for peak in accepted:\n"
    "        left, right = max(0, peak - search), min(len(ecg), peak + search + 1)\n"
    "        refined.append(left + np.argmax(ecg[left:right]))\n"
    "    return np.unique(np.asarray(refined, dtype=int))\n"
    "\n"
    "\n"
    "def create_r_centered_beats(ecg, labels, r_peaks, pre=PRE, post=R5_POST):\n"
    "    X, Y, kept_r = [], [], []\n"
    "    for r in r_peaks:\n"
    "        left, right = r - pre, r + post\n"
    "        if left < 0 or right > len(ecg):\n"
    "            continue\n"
    "        X.append(ecg[left:right]); Y.append(labels[left:right]); kept_r.append(r)\n"
    "    return np.asarray(X, dtype=np.float32), np.asarray(Y, dtype=np.int64), np.asarray(kept_r, dtype=int)\n"
    "\n"
    "\n"
    "def ludb_labels_at_250(annotation, original_length):\n"
    "    labels = np.zeros(round(original_length / 2), dtype=np.int64)\n"
    "    start, kind = None, None\n"
    "    for sample, symbol in zip(annotation.sample, annotation.symbol):\n"
    "        if symbol == \"(\":\n"
    "            start, kind = sample, None\n"
    "        elif symbol == \"p\":\n"
    "            kind = 1\n"
    "        elif symbol == \"N\":\n"
    "            kind = 2\n"
    "        elif symbol == \"t\":\n"
    "            kind = 3\n"
    "        elif symbol == \")\" and start is not None and kind is not None:\n"
    "            left, right = round(start / 2), round(sample / 2)\n"
    "            labels[left:right + 1] = kind\n"
    "            start, kind = None, None\n"
    "    return labels\n"
    "\n"
    "\n"
    "def build_qtdb_r5_beats():\n"
    "    records = sorted({path.stem for path in QTDB_DIR.glob(\"*.dat\")})\n"
    "    X_parts, Y_parts, record_ids = [], [], []\n"
    "    for record_name in records:\n"
    "        path = QTDB_DIR / record_name\n"
    "        try:\n"
    "            record = wfdb.rdrecord(str(path))\n"
    "            ecg = record.p_signal[:, 0].astype(np.float32)\n"
    "            labels = to_pt_labels(generate_labels(ecg, wfdb.rdann(str(path), \"pu0\")))\n"
    "            r_peaks = pan_tompkins_r_peaks(ecg, float(record.fs))\n"
    "            X, Y, _ = create_r_centered_beats(ecg, labels, r_peaks, pre=PRE, post=R5_POST)\n"
    "            if not len(X):\n"
    "                continue\n"
    "            X_parts.append(X); Y_parts.append(Y); record_ids.extend([record_name] * len(X))\n"
    "        except Exception as error:\n"
    "            print(f\"Skipped {record_name}: {error}\")\n"
    "    X_r5 = np.concatenate(X_parts); Y_r5 = np.concatenate(Y_parts)\n"
    "    return X_r5, Y_r5, np.asarray(record_ids)\n"
    "\n"
    "\n"
    "def build_ludb_r5_beats():\n"
    "    X_parts, Y_parts, record_ids = [], [], []\n"
    "    for header in sorted(LUDB_DIR.glob(\"*.hea\")):\n"
    "        path = str(header.with_suffix(\"\"))\n"
    "        record = wfdb.rdrecord(path)\n"
    "        lead = record.sig_name.index(\"ii\")\n"
    "        signal = resample_poly(record.p_signal[:, lead].astype(np.float32), up=1, down=2)\n"
    "        annotation = wfdb.rdann(path, \"ii\")\n"
    "        labels = ludb_labels_at_250(annotation, len(record.p_signal))\n"
    "        size = min(len(signal), len(labels)); signal, labels = signal[:size], labels[:size]\n"
    "        labels = to_pt_labels(labels)\n"
    "        r_peaks = pan_tompkins_r_peaks(signal, 250.0)\n"
    "        X, Y, _ = create_r_centered_beats(signal, labels, r_peaks, pre=PRE, post=R5_POST)\n"
    "        if len(X):\n"
    "            X_parts.append(X); Y_parts.append(Y); record_ids.extend([header.stem] * len(X))\n"
    "    X_ludb_r5 = np.concatenate(X_parts); Y_ludb_r5 = np.concatenate(Y_parts)\n"
    "    return X_ludb_r5, Y_ludb_r5, np.asarray(record_ids)\n"
    "\n"
    "\n"
    "# Build data (no training). This may take a minute.\n"
    "X_r5, Y_r5, r5_record_ids = build_qtdb_r5_beats()\n"
    "r5_train_records, r5_val_records = train_test_split(np.unique(r5_record_ids), test_size=0.20, random_state=7, shuffle=True)\n"
    "r5_train_mask = np.isin(r5_record_ids, r5_train_records)\n"
    "r5_val_mask = np.isin(r5_record_ids, r5_val_records)\n"
    "r5_mean, r5_std = X_r5[r5_train_mask].mean(), X_r5[r5_train_mask].std()\n"
    "\n"
    "X_ludb_r5, Y_ludb_r5, ludb_ids_r5 = build_ludb_r5_beats()\n"
    "\n"
    "# R3 was trained with the shared R1 normalization.\n"
    "norm = np.load(NORMALIZATION_LOAD_PATH)\n"
    "train_mean, train_std = norm[\"train_mean\"], norm[\"train_std\"]\n"
    "\n"
    "\n"
    "# Model definitions\n"
    "class CNNFeatureExtractor(nn.Module):\n"
    "    def __init__(self):\n"
    "        super().__init__()\n"
    "        self.features = nn.Sequential(\n"
    "            nn.Conv1d(1, 32, kernel_size=7, padding=3), nn.BatchNorm1d(32), nn.ReLU(),\n"
    "            nn.Conv1d(32, 64, kernel_size=5, padding=2), nn.BatchNorm1d(64), nn.ReLU(),\n"
    "        )\n"
    "    def forward(self, x):\n"
    "        return self.features(x)\n"
    "\n"
    "\n"
    "class BiLSTMBlock(nn.Module):\n"
    "    def __init__(self):\n"
    "        super().__init__()\n"
    "        self.lstm = nn.LSTM(64, 128, num_layers=1, batch_first=True, bidirectional=True)\n"
    "    def forward(self, x):\n"
    "        return self.lstm(x)[0]\n"
    "\n"
    "\n"
    "class RPeakGuidedML2(nn.Module):\n"
    "    def __init__(self, num_classes=3):\n"
    "        super().__init__()\n"
    "        self.cnn = CNNFeatureExtractor()\n"
    "        self.bilstm = BiLSTMBlock()\n"
    "        self.dropout = nn.Dropout(0.3)\n"
    "        self.classifier = nn.Linear(256, num_classes)\n"
    "    def forward(self, x):\n"
    "        x = self.cnn(x).permute(0, 2, 1)\n"
    "        x = self.bilstm(x)\n"
    "        return self.classifier(self.dropout(x))\n"
    "\n"
    "\n"
    "class RPeakTimeML2(nn.Module):\n"
    "    def __init__(self, num_classes=3):\n"
    "        super().__init__()\n"
    "        self.cnn = nn.Sequential(\n"
    "            nn.Conv1d(2, 32, kernel_size=7, padding=3), nn.BatchNorm1d(32), nn.ReLU(),\n"
    "            nn.Conv1d(32, 64, kernel_size=5, padding=2), nn.BatchNorm1d(64), nn.ReLU(),\n"
    "        )\n"
    "        self.bilstm = nn.LSTM(64, 128, num_layers=1, batch_first=True, bidirectional=True)\n"
    "        self.dropout = nn.Dropout(0.3)\n"
    "        self.classifier = nn.Linear(256, num_classes)\n"
    "    def forward(self, x):\n"
    "        x = self.cnn(x).permute(0, 2, 1)\n"
    "        return self.classifier(self.dropout(self.bilstm(x)[0]))\n"
    "\n"
    "\n"
    "def with_time_channel(signals, pre=PRE, post=R5_POST):\n"
    "    time = (np.arange(signals.shape[1], dtype=np.float32) - pre) / post\n"
    "    return np.stack([signals.astype(np.float32), np.broadcast_to(time, signals.shape)], axis=1).copy()\n"
    "\n"
    "\n"
    "device = torch.device(\"mps\" if torch.backends.mps.is_available() else \"cuda\" if torch.cuda.is_available() else \"cpu\")\n"
    "print(f\"Device: {device}\")\n"
    "\n"
    "# ---- R3: QTDB validation predictions (Figure 3) ----\n"
    "X_val = (X_r5[r5_val_mask] - train_mean) / train_std\n"
    "Y_val = Y_r5[r5_val_mask]\n"
    "val_loader_r3 = DataLoader(TensorDataset(torch.tensor(X_val).unsqueeze(1), torch.tensor(Y_val)), batch_size=BATCH_SIZE, shuffle=False)\n"
    "\n"
    "model_r3 = RPeakGuidedML2().to(device)\n"
    "model_r3.load_state_dict(torch.load(MODEL_LOAD_PATH_R3, map_location=device))\n"
    "model_r3.eval()\n"
    "print(f\"Loaded R3 model from {MODEL_LOAD_PATH_R3}\")\n"
    "\n"
    "r3_predictions, r3_labels = [], []\n"
    "with torch.no_grad():\n"
    "    for batch_x, batch_lab in val_loader_r3:\n"
    "        r3_predictions.append(model_r3(batch_x.to(device)).argmax(dim=2).cpu().numpy())\n"
    "        r3_labels.append(batch_lab.numpy())\n"
    "r3_predictions = np.concatenate(r3_predictions)\n"
    "r3_labels = np.concatenate(r3_labels)\n"
    "print(f\"R3 QTDB val predictions: {r3_predictions.shape}\")\n"
    "\n"
    "# ---- R3: LUDB predictions (Figure 4 baseline) ----\n"
    "X_ludb_norm = (X_ludb_r5 - train_mean) / train_std\n"
    "r3_ludb_predictions = []\n"
    "with torch.no_grad():\n"
    "    for start in range(0, len(X_ludb_norm), BATCH_SIZE):\n"
    "        batch = torch.tensor(X_ludb_norm[start:start + BATCH_SIZE], dtype=torch.float32).unsqueeze(1).to(device)\n"
    "        r3_ludb_predictions.append(model_r3(batch).argmax(dim=2).cpu().numpy())\n"
    "r3_ludb_predictions = np.concatenate(r3_ludb_predictions)\n"
    "print(f\"R3 LUDB predictions: {r3_ludb_predictions.shape}\")\n"
    "\n"
    "# ---- R6: LUDB untouched test predictions (Figure 4 proposed) ----\n"
    "r6_test_records = train_test_split(np.unique(ludb_ids_r5), test_size=0.90, random_state=17, shuffle=True)[1]\n"
    "r6_test_mask = np.isin(ludb_ids_r5, r6_test_records)\n"
    "r6_ludb_test_x = with_time_channel((X_ludb_r5[r6_test_mask] - r5_mean) / r5_std)\n"
    "r6_truth = Y_ludb_r5[r6_test_mask]\n"
    "\n"
    "r6_ludb_model = RPeakTimeML2().to(device)\n"
    "r6_ludb_model.load_state_dict(torch.load(MODEL_LOAD_PATH_R6_LUDB, map_location=device))\n"
    "r6_ludb_model.eval()\n"
    "print(f\"Loaded R6 LUDB-adapted model from {MODEL_LOAD_PATH_R6_LUDB}\")\n"
    "\n"
    "r6_predictions = []\n"
    "with torch.no_grad():\n"
    "    for start in range(0, len(r6_ludb_test_x), BATCH_SIZE):\n"
    "        batch = torch.tensor(r6_ludb_test_x[start:start + BATCH_SIZE]).to(device)\n"
    "        r6_predictions.append(r6_ludb_model(batch).argmax(dim=2).cpu().numpy())\n"
    "r6_predictions = np.concatenate(r6_predictions)\n"
    "print(f\"R6 LUDB test predictions: {r6_predictions.shape}\")\n"
    "\n"
    "print(\"\\nAll variables ready for the Figure 3 + Figure 4 cell.\",\n"
    "      \"Set QTDB_IDX / LUDB_IDX there as desired.\")\n"
)

code_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": code_src.splitlines(keepends=True),
}

# Insert the two new cells just before the existing Figure 3 + Figure 4 cell (index 79).
insert_pos = 79
nb["cells"][insert_pos:insert_pos] = [markdown_cell, code_cell]

with open(NB_PATH, "w") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
    f.write("\n")

print(f"Inserted 2 cells at position {insert_pos}. New total cells: {len(nb['cells'])}")
print(f"Backup saved to {BAK_PATH}")
